# cafe_robot/config/slam_config.yaml
slam_toolbox:
  ros__parameters:
    # Robot frame setup
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    
    # SLAM modes - online_async is best for mapping
    mode: online_async
    
    # Mapping parameters
    resolution: 0.05
    max_laser_range: 10.0
    map_update_interval: 5.0
    transform_publish_period: 0.2
    map_start_pose: [0.0, 0.0, 0.0]
    use_scan_matching: true
    use_scan_barycenter: true
    
    # Loop closure parameters
    enable_interactive_mode: false
    loop_search_distance: 3.0
    minimumTravelDistance: 0.5
    minimumTravelHeading: 0.5
    
    # Advanced parameters
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5